version: '3.8'

services:
  semaphore-mysql:
    ports:
      - 3306:3306
    image: mysql:5.6
#    platform: linux/x86_64   # for apple M1 chip
    hostname: semaphore-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore

  semaphore:
    build:
        context: ./docker
        args:
          http_proxy: ${http_proxy:-}
          https_proxy: ${http_proxy:-}
    ports:
      - 3100:3000
    image: mwallraf/ansiblesemaphore-oracle:1.0
#    platform: linux/x86_64   # for apple M1 chip
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: semaphore-mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: Admin123
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      http_proxy: ${http_proxy:-}
      https_proxy: ${http_proxy:-}
    depends_on:
      - semaphore-mysql

networks:
  default:
    name: ansible_semaphore
    ipam:
      config:
        - subnet: 198.51.102.100/24
